{
 "title": "Kepler + vLLM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "LLM Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vllm:avg_generation_throughput_toks_per_s",
     "legendFormat": "{{model_name}}"
    },
    {}
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kepler_container_gpu_joules_total{container_name=~\"vllm-container.*\"}[1m]))",
     "legendFormat": "GPU"
    },
    {
     "expr": "sum(rate(kepler_container_package_joules_total{container_name=~\"vllm-container.*\"}[1m]))",
     "legendFormat": "CPU Package"
    }
   ]
  },
  {
   "title": "Performance per Watt Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "\nsum(rate(kepler_container_joules_total{container_name=~\"vllm-container-llama-13b-gptq.*\"}[1m]))/sum(vllm:avg_generation_throughput_toks_per_s{model_name=\"TheBloke/Llama-2-13B-chat-GPTQ\"})",
     "legendFormat": "LLama-2-13B-chat-GPTQ"
    },
    {
     "expr": "sum(rate(kepler_container_joules_total{container_name=~\"vllm-container-llama-7b-gptq.*\"}[1m]))/sum(vllm:avg_generation_throughput_toks_per_s{model_name=\"TheBloke/Llama-2-7B-chat-GPTQ\"})",
     "legendFormat": "LLama-2-7B-chat-GPTQ"
    }
   ]
  }
 ]
}