{
 "title": "vLLM Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model",
    "label": "model_name",
    "query": {
     "query": "label_values(vllm:avg_generation_throughput_toks_per_s, model_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "vllm:num_requests_running{model_name=\"$model\"}",
     "legendFormat": "Running Requests"
    },
    {
     "expr": "vllm:num_requests_swapped{model_name=\"$model\"}",
     "legendFormat": "Requests Swapped"
    },
    {
     "expr": "vllm:num_requests_waiting{model_name=\"$model\"}",
     "legendFormat": "Requests Waiting"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "End2end Request Latency Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (vllm:e2e_request_latency_seconds_bucket{model_name=\"$model\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to First Token Seconds Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (vllm:time_to_first_token_seconds_bucket{model_name=\"$model\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Output Token Seconds Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (vllm:time_per_output_token_seconds_bucket{model_name=\"$model\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Prompt Throughput for $model",
   "type": "timeseries",
   "description": "The model input prompt throughput (tokens/sec)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "vllm:avg_prompt_throughput_toks_per_s{model_name=\"$model\"}",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Generation Throughput for $model",
   "type": "timeseries",
   "description": "The model generation throughput (tokens/sec)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "vllm:avg_generation_throughput_toks_per_s{model_name=\"$model\"}",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  { "title": "System Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "GPU KVCache Utilization",
   "type": "timeseries",
   "description": "The percentage of KV Cache Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "vllm:gpu_cache_usage_perc{model_name=\"$model\"}",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "CPU Cache Utilization",
   "type": "timeseries",
   "description": "The percentage of CPU Cache Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "vllm:cpu_cache_usage_perc{model_name=\"$model\"}",
     "legendFormat": "{{model_name}}"
    }
   ]
  }
 ]
}